version: '3.9'

services:
  backend:
    build: ./app
    env_file:
      - .env
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: python main.py
    environment:
      - ENV=development
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
    #   interval: 10s       # Check every 10 seconds
    #   retries: 5          # Try 5 times before failing
    #   start_period: 30s   # Give the container 30s to start up
    #   timeout: 5s         # Allow the check 5s to complete

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false
    # depends_on:
    #   backend:
    #     condition: service_healthy
